export default {
    login: 'အကောင့်ဝင်ပါ',
    register: 'အကောင့်အသစ်ဖွင့်ပါ',
    emailPlaceholder: 'အီးမေးလ်....',
    next: 'နောက်တဆင့်သို့',
    noAcc: 'အကောင့်မရှိပါက',
    haveAcc: 'အကောင့်ရှိပါက ',
    security: 'လုံခြုံရေးအဆင့်',
    passwordPlaceholder: 'လျှို့ဝှက်နံပတ်....',
    savePwd: 'လျှို့ဝှက်နံပတ် မှတ်ထားပါ',
    conPwdPlaceholder: 'လျှို့ဝှက်နံပတ် အတည်ပြုပါ....',
    back: 'နောက်သို့',
    sankyu: 'အဆုံးထိကြည့်ပေးတဲ့အတွက် ကျေးဇူးတင်ပါတယ်',
    logout: 'ထွက်ရန်',
}   